### ISSUE TITLE
Synchronization of redis databases

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#28] opened 2015-12-17 06:42 UTC
I just hope to see a synchronization between hosts, because it is hard to keep the same settings on all the servers. Carmethene on IRC proposed to use http://redis.io/topics/replication. I know about possibility to use redis over internet, but i am afraid of lags it may cause. Maybe async operations with local cache will helps, idk.

**Comment by MinoMino** [comment] 2015-12-17 17:57
I would not use it over internet. You'd probably get lag all the time if you did so. I also don't think replication would work because it's a master-slave setup where slaves are read-only. I also think slave queries can be blocking during synchronization, so that would be a potential issue too.

In any case, the fact that DB stuff isn't threaded is by design. Moving it to threads would severely cripple the functionality of minqlx because it would have to pass all events to the engine right away or disallow DB usage in most events. Neither of those are options I would consider.

**Closed as completed** 2015-12-17 17:57 UTC
Labels: wontfix
