### ISSUE TITLE
Big mappool file causes a disconnect when using !mappool command

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#14] opened 2015-11-09 22:59 UTC
I see that you just copied stuff to else statement, where minqlx is seaching for mappool in fs_homepath. Mappool not loading when placed at main baseq3 folder.

**Comment by Melodeiro** [comment] 2015-11-09 23:18
Nevermind, i had a typo in my launch script

**Comment by Melodeiro** [comment] 2015-11-10 22:35
Ok, i just dont tested it enough. Now client disconnects when i type !mappool with error: "CL_GetServerCommand: a reliable command was cycled out". Probably caused by same thing - else statement.

**Comment by MinoMino** [comment] 2015-11-10 23:57
No idea what you mean with "else statement", but I doubt that's relevant. That's likely caused by a map pool with way too many maps for the client to be able to receive it all at once.

I'm not exactly sure what the character limit is, but the default of 100 I've got on the tell channel is lower for sure. You could try changing [this line](https://github.com/MinoMino/minqlx-plugins/blob/master/essentials.py#L715) to `player.tell(out.rstrip("\n"), delimiter="\n", limit=400)` and see if that works. Alternatively, you could paste your map pool here and I can do some testing.

**Comment by Melodeiro** [comment] 2015-11-11 05:14
I talking about this [line](https://github.com/MinoMino/minqlx-plugins/blob/master/essentials.py#L97), but now i see, there is mpbase and mphome, so else statement is different.

Changing limit to 400 works well, thanks. My mappool is too big, because i didnt filtered out maps in it yet. Anyway, here is one example for testing: http://pastebin.com/fY9UU5nF

**Comment by MinoMino** [comment] 2015-11-12 03:09
Yeah, it's to keep the precedence order QLDS has, fs_homepath > fs_basepath.

Good to hear upping the limit works. I'll do some quick testing with the pastebin you provided and push the change if I don't find any issues with it. Thanks.

**Comment by MinoMino** [comment] 2015-11-26 05:20
Addressed in the above commit. Long map pools work fine without explicitly passing a limit.

**Closed as completed by MinoMino** 2015-11-26 05:20 UTC
Labels: bug
