### ISSUE TITLE
when QLSTATS server return 9999 (deleted profile) mod start to do wrong things

### ISSUE THREAD

**Issue by sanivitae** [MinoMino/minqlx#95] opened 2020-03-11 17:28 UTC
when QLSTATS server return 9999 (deleted profile) mod start to do wrong things
1. not balanced shuffle (bcz of 9999)
2. cant in game bcz of limits ELO

can you make then 9999 ELO returns from QLSTATS mod make it like 1300 or 1500

**Comment by em92** [comment] 2020-03-12 05:23
> For those who do not want to be rated at all, they can use the "Delete Account" function. That will anonymize the existing data and mark the steam-id so that no further data will be collected.

Reference: https://www.plusforward.net/quake/post/50034/Upcoming-changes-for-GDPR-compliance/#cid4494

So untracked player does not have rating like other players, 'cos he refuses and denies to have it. And for sure, it is not expected to have balanced game with this player.

Possible solutions:
1. Block such players using [qlstats_privacy_policy](https://github.com/mgaertne/minqlx-plugin-tests/blob/master/src/main/python/qlstats_privacy_policy.py) plugin by @mgaertne or using rating limiting plugins as you mentioned.
2. Set rating manually to individual players. `balance` plugin has command `!setrating` for that. Don't know how rating limiting plugins deal with it.

**Comment by mgaertne** [comment] 2020-03-12 07:24
Richt now, qlstats_privacy_policy does not check whether a player has been set with a local rating, so it goes with whatever you have set for the policy enacted. If the players need to be tracked, he will still be kicked or made unavailable to join.

I'm twisting the idea of a plugin to have server-based ratings similar to what qlstats does, but only on a local server level for some time now, with the potential to have elos per map and server of some sorts. Not sure whether I will implement that anytime, but such a plugin could also adjust the local ratings over time on your own server. Not sure about data privacy there, though.

**Comment by em92** [comment] 2020-03-12 07:48
> Richt now, qlstats_privacy_policy does not check whether a player has been set with a local rating

I don't think it is required. It deals with policy only by design, isn't it?

> I'm twisting the idea of a plugin to have server-based ratings similar to what qlstats does, but only on a local server level for some time now, with the potential to have elos per map and server of some sorts. Not sure whether I will implement that anytime, but such a plugin could also adjust the local ratings over time on your own server. Not sure about data privacy there, though.

How about this? https://github.com/em92/quakelive-local-ratings

**Comment by em92** [comment] 2020-03-25 09:40
Closing words: works as intended

**Closed as completed by em92** 2020-03-25 09:40 UTC

**Comment by sanivitae** [comment] 2020-03-25 18:18
Possible solutions:

1. Block such players using qlstats_privacy_policy plugin by @mgaertne or using rating limiting plugins as you mentioned.

Yeee Block users - its good idea =\
Can't come up with something better ???

2. Set rating manually to individual players. balance plugin has command !setrating for that. Don't know how rating limiting plugins deal with it.****

manually? That is, to contact 50 server administrators and tell all of them to set their rating on 75 servers?
And what to do when 1 month of account blocking on QLSTATS passes - contact again with 50 administrators so that they remove the rating?
STUPID DECISIONS I HAVE NOT SEEN ANYTHING !!!!!

**Comment by em92** [comment] 2020-03-26 06:55
@sanivitae those possible solutions were for server admins if they accept untracked players in their servers. Possible solution for players - switch back from untracked to anonymous and stop jerking around (перестать морочить голову).

**Comment by sanivitae** [comment] 2020-03-26 09:17
А кто морочит? я по существу.
Почему это должна быть моя проблема, а не плагина, который не в состоянии
адекватно реагировать на коды qlstats и пускать плееров на сервера?

чт, 26 марта 2020 г., 8:56 Eugene Molotov <notifications@github.com>:

**Comment by em92** [comment] 2020-03-26 11:51
> А кто морочит? я по существу.

Это ложь!

> Почему это должна быть моя проблема, а не плагина, который не в состоянии адекватно реагировать на коды qlstats и пускать плееров на сервера?

Потому-что ты запрещаешь высчитывать рейтинг.

В добавок даже если всем untracked игрокам выставить 1500 или 1300, то этот игрок делает проблемы тем, с кем он играет, ибо с чего вдруг у игрока рейтинг 1500? Может он играет на 900 или на 2000? После shuffle, команды не будут сбаланисрованными в любом случае. Примерно такую-же мысль я озвучил в своем первом сообщении:

> So untracked player does not have rating like other players, 'cos he refuses and denies to have it. And for sure, it is not expected to have balanced game with this player.

В итоге не надо обманывать, мол имбовые команды получилось, потому-что 9999. Имбовые команды получились, потому-что игрок без рейтинга на сервере.

Решение я уже озвучил - даем добро qlstats высчитывать рейтинг.

**Comment by sanivitae** [comment] 2020-03-26 15:29
Мне кажется последний зарегистрированный рейтинг игрока на сервере и должен
быть заморожен и отображаться в процессе блокировки месячной....

мне еще и в QLstats разработчикам писать?


чт, 26 марта 2020 г., 13:51 Eugene Molotov <notifications@github.com>:

**Comment by em92** [comment] 2020-03-27 07:55
> Мне кажется последний зарегистрированный рейтинг игрока на сервере и должен быть заморожен и отображаться в процессе блокировки месячной....

Игрок специально играет плохо, потом замораживает себе рейтинг и последующие игры имбовые, где он в команде мечты. Короче говоря, такое быть не должно.

> мне еще и в QLstats разработчикам писать?

Одному уже пишешь. https://github.com/PredatH0r/XonStat/commits?author=em92
